version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:9.4
    networks:
      - noosfero-net
    env_file:
      - config/docker/prod/production.env
    volumes:
      - pg-prod-data:/var/lib/postgresql/data

  noosfero:
    container_name: noosfero
    build:
      context: .
      dockerfile: ./config/docker/prod/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./tmp/backup:/dump
    networks:
      - noosfero-net
    env_file:
      - config/docker/prod/production.env 

volumes:
  pg-prod-data: {}

networks:
  noosfero-net:
    name: noosfero-net
