source "https://rubygems.org"

gem 'omniauth', '~> 1.9'
gem 'omniauth-facebook', '~> 5.0'
gem 'omniauth-twitter', '~> 1.4'
gem "omniauth-google-oauth2", '~> 0.6.1'
gem 'omniauth-oauth2', '~> 1.6'
gem "omniauth-github", '~> 1.3'
