# This file contains default settings to tinymce editor

mobile:
  - theme: 'mobile'

image_advtab: true

relative_urls : false
remove_script_host : true

plugins:
  - advlist
  - autolink
  - lists
  - link
  - image
  - charmap
  - print
  - preview
  - hr
  - anchor
  - pagebreak
  - searchreplace
  - wordcount
  - visualblocks
  - visualchars
  - code
  - fullscreen
  - insertdatetime
  - media
  - nonbreaking
  - save
  - table
  - contextmenu
  - directionality
  - emoticons
  - template
  - paste
  - textcolor
  - colorpicker
  - textpattern
